down:
	wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
	mv Mini* /tmp

install:
	#mkdir /data2/$USER
	sudo mkdir -p /data/tmpconda
	sudo chown -R tony /data
	TMPDIR=/data/tmpconda bash /tmp/Miniconda3-latest-Linux-x86_64.sh


