cat:
	cat Makefile
down:
	wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
	mv Mini* /tmp

install:
	#mkdir /data2/$USER
	sudo mkdir -p /data/tmpconda
	sudo chown -R ec2-user /data
	TMPDIR=/data/tmpconda bash /tmp/Miniconda3-latest-Linux-x86_64.sh


docker:
	sudo yum install docker
	sudo usermod -aG docker ${USER}
	sudo systemctl enable docker
	sudo systemctl start docker


install-s3fs-centos:
	sudo yum install epel-release   # amazons version
	sudo yum install s3fs-fuse
